export const GET_EMPLOYEE_LIST_REQUEST = "GET_EMPLOYEE_LIST_REQUEST";
export const GET_EMPLOYEE_LIST_SUCCESS = "GET_EMPLOYEE_LIST_SUCCESS";
export const GET_EMPLOYEE_LIST_FAILURE = "GET_EMPLOYEE_LIST_FAILURE";

export const GET_EMPLOYEE_BYID_REQUEST = "GET_EMPLOYEE_BYID_REQUEST";
export const GET_EMPLOYEE_BYID_SUCCESS = "GET_EMPLOYEE_BYID_SUCCESS";
export const GET_EMPLOYEE_BYID_FAILURE = "GET_EMPLOYEE_BYID_FAILURE";

export const UPDATE_EMPLOYEE_BYID_REQUEST = "UPDATE_EMPLOYEE_BYID_REQUEST";
export const UPDATE_EMPLOYEE_BYID_SUCCESS = "UPDATE_EMPLOYEE_BYID_SUCCESS";
export const UPDATE_EMPLOYEE_BYID_FAILURE = "UPDATE_EMPLOYEE_BYID_FAILURE";

export const CREATE_EMPLOYEE_REQUEST = "CREATE_EMPLOYEE_REQUEST";
export const CREATE_EMPLOYEE_SUCCESS = "CREATE_EMPLOYEE_SUCCESS";
export const CREATE_EMPLOYEE_FAILURE = "CREATE_EMPLOYEE_FAILURE";

export const DELETE_EMPLOYEE_BYID_REQUEST = "DELETE_EMPLOYEE_BYID_REQUEST";
export const DELETE_EMPLOYEE_BYID_SUCCESS = "DELETE_EMPLOYEE_BYID_SUCCESS";
export const DELETE_EMPLOYEE_BYID_FAILURE = "DELETE_EMPLOYEE_BYID_FAILURE";